[package]
name = "mize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "server"
path = "src/server-main.rs"

[[bin]]
name = "client"
path = "src/client-main.rs"

[dependencies]
futures-util = "0.3.24"
surrealdb = "1.0.0-beta.7"
tokio = {version = "1.21.0", features = ["full"]}
tokio-stream = "0.1.9"
warp = "0.3.2"
