
[[error]]
code = 11
category = "don't know yet"
message = "Something went wrong. //TODO: give this error it's own category and code."

[[error]]
category = "data_storage"
code = 28
message = "Something went wrong in the data storage."

[[error]]
code = 29
category = "data_storage:surrealdb_error"
message = "Something went wrong internally with the data-storage (surrealdb/rocksdb): {}"

[[error]]
code = 30
category = "data_storage:surrealdb_error"
message = "Could not create data_storeage at {}"

[[error]]
code = 31
category = "data_storage:surrealdb_error"
message = "No item with id 0. There definetly should be one"

[[error]]
code = 32
category = "data_storage"
message = "item {} was not found in storage"

[[error]]
code = 100
category = "don't know yet"
message = "You can't delete item number 0. This item contains mandatory Config for the Server."

[[error]]
code = 101
category = "key_missing::item0::num_of_items"
message = "num_of_items missing in item0"

[[error]]
code = 102
category = "key_missing::item0::next_free_id"
message = "next_free_id missing in item0"

[[error]]
message = "_commit missing in item0"
code = 103
category = "key_missing::item0::_commit"

[[error]]
message = "_commit missing"
code = 103
category = "key_missing::_commit"

[[error]]
code = 104
category = "data_storage::index_not_found"
message = "could not read index of item"

[[error]]
code = 105
category = "don't know yet"
message = "_commit not 8 bytes long"

[[error]]
code = 106
category = "parse_error"
message = "error while parsing to an int"

[[error]]
code = 107
category = "faulty_message"
message = "some error with message sent to the server"

[[error]]
code = 108
category = "faulty_message"
message = "There was not metadata in a message, that should have some."

[[error]]
code = 109
category = "faulty_message"
message = "something that should be utf8 valid was not"

[[error]]
code = 111
category = "faulty_update"
message = "mize-commit can't be updated manually"

[[error]]
code = 113
category = "don't know yet"
message = "module header not a String"

[[error]]
code = 114
category = "error with error system"
message = "the error with code {} was not found in the errors.toml file"

[[error]]
code = 115
category = "WebSocket Error"
message = "Error reviecing a message from the WebSocket"


